### ISSUE TITLE
[3주차] (인터페이스/추상클래스는 항상 옳을까 ?)

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2024Study-Objects#16]
### 페이지
89
-----
## 궁금한 내용

1장, 2장, 3장을 거치며 매번 나오는 개념인 추상화. 

이런 추상화를 위해서는 인터페이스 혹은 추상 클래스의 사용이 필수적으로 느껴지는데요, 

이번 장 역할에서도 공통적인 책임을 수행하는 역할을 표현하기 위해서는 인터페이스와 추상클래스의 사용을 이야기했는데요, 

잘 변경되지 않을 클래스 / 역할을 수행할 객체가 단일이라도 인터페이스 혹은 추상클래스를 무조건적으로 구현하는 것이 옳을까요 ?

**Comment by tgyuuAn** [comment]
정리하자면,

현재 요구사항에서 **다형성이 필요하거나 테스트 코드를 작성할 때 Fake 객체가 필요할 때**, 혹은 **의존성 역전이 필요할 때** 인터페이스 같은 추상화를 두고 작성.

그것이 아닐 경우 당장 지금에서는 **불필요한 추상화를 사용하여 코드의 가독성을 떨어트리는 것을 지양**하자.
