### ISSUE TITLE
[3주차] 협력을 위해서 필요한 객체 -> 상태? 매개변수?

### ISSUE THREAD

**Issue by HyeonJun-Jung** [pknu-wap/2024Study-Objects#19]
### 페이지
None
-----
## 궁금한 내용
협력을 하기 위해서 다른 객체가 필요하다고 한다면, 이 객체를 매개변수로서 받아올 지 아니면 클래스 내부의 상태로 들고 있을 지 판단하는 기준이 뭘까요?
저는 보통 클래스 메소드 대부분과 관련이 있거나 내부에서 관리될 필요가 있는 경우라면 상태로서 관리하는 것 같습니다. 여러분들은 어떤가요?

**Comment by tgyuuAn** [comment]
1. 객체의 생성자에서 객체를 넘겨주는 방법
2. 객체의 내부에서 해당 인스턴스를 생성하는 방법
3. 메서드의 파라미터로 넘겨주는 방법

**Comment by jeongjaino** [comment]
런타임에 의존성을 바꾸기 위해서는 2번을 사용

1번의 경우는 외부에서 데이터를 가공해서 주입하는 경우

1번과 2번 적절히 사용해야 한다.

**Comment by HyeonJun-Jung** [comment]
1번과 2번을 동시에 사용?!

**Comment by HyeonJun-Jung** [comment]
> 1번과 2번을 동시에 사용?!

1번으로 초기 객체 설정 후, 2번을 통해 런타임 의존성 설정
