### ISSUE TITLE
[4주차] (캡슐화 위반)

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2024Study-Objects#24]
### 페이지
4장

-----
## 궁금한 내용

캡슐화 위반의 케이스가 게터를 통해서 내부적인 상태에 접근하는 경우, 파라미터 타입을 통해서 유추하는 경우 캡슐화 위반으로 말하는 것을 처음 알게 되었는데요 ! 

게터와 파라미터 타입과 같이 캡슐화 위반을 대응하는 방법은 어떤 게 있을까요 ? 

또한, 협력이라는 관점에서 게터와 타입 파라미터가 필수적일 수 밖에 없는 경우가 있을 것 같은데, 캡슐화 위반이 너무 가혹한 것은 아닐까 라는 생각도 드네요.

**Comment by 9kyo-hwang** [comment]
무분별한 Getter는 지양하는 것이 좋다.
하지만 파라미터 타입 유추를 통한 캡슐화 위반은.... 현실적으로 힘든 부분이 좀 있는 듯 하다.
