### ISSUE TITLE
[6주차] (함수형 프로그래밍과 객체지향 프로그래밍 패러다임)

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2024Study-Objects#27]
### 페이지
6장

-----
## 궁금한 내용

제가 사용하는 코틀린은 함수형과 객체지향을 모두 지원하는 하이브리드 언어로 표현을 많이 하는데요, 

객체 지향 패러다임과 함수형 패러다임은 서로 상충되는 개념인지, 서로 접목이 가능한 패러다임인지 궁금합니다. 

이번 장에서 쿼리에 대해 이야기가 많이 나왔는데, 그런 측면에서 함수형 프로그래밍과 과연 전혀 다른 패러다임일까?에 대한 생각이 들었네요 

- 함수형 프로그래밍 패러다임은 순수함수 / 함수를 매개변수로 넘기는 것에 대한 정의겠지만서도요

**Comment by jeongjaino** [comment]
https://f-lab.kr/insight/functional-vs-oop

**Comment by jeongjaino** [comment]
https://www.inflearn.com/pages/infcon-2023-tech-oopfp?srsltid=AfmBOorz_LiQRkzd3mEiIJpdYYKUQ5ZTTAxQgvronWsIeYCsSuYLrfj_

**Comment by tgyuuAn** [comment]
함수형 프로그래밍은 **똑같은 Input에 대해서 매번 똑같은 Output을 출력**하는 **멱등성**이 중요하다고 생각하는데요,

객체지향 프로그래밍에서 말하는 객체라는 것을 사용하게 되면 클래스 내부에 stateful 한 상태를 계속 홀딩하고 있어야 하기 때문에,

**똑같은 인스턴스를 넣어도 내부에 쥐고있는 객체의 상태에 따라 값이 달라질 수도 있다고 생각됩니다.**

<br><br><br>

재사용성의 관점이나 결합도 및 응집도 등등의 관점에서 객체지향 프로그래밍이 각광을 받고 있지만,

그 사이에서 함수형 프로그래밍의 강력한 장점 중 하나인 `Stateless를 테스트 하기에 디버깅이 쉽다`와 `코드를 보고 유추하기 쉽다`라는 점을 이용해서

코틀린과 같은 요즘 언어에서 객체지향을 베이스로 함수형 프로그래밍의 성질을 같이 사용하는 형태로 사용하는 것 같습니다.

<br><br><br>

**결론만 말하자면 두 개념은 상충되는 개념이 아니며, 함께 사용할 수도 있는 개념이다.**

**하지만, 객체지향은 상태를 Stateful로 관리해야 한다는 점에서 부분적으로 같이 사용할 수 없는 부분도 있을 수 있다.**

인 것 같습니다...!

**Comment by jeongjaino** [comment]
@tgyuuAn YAMUCHI TGYUU ㄷㄷㄷㄷㄷㄷㄷ
