### ISSUE TITLE
[1주차] Bag과 TicketOffice에서 자율적으로 만들면서 의존성이 추가가 된 경우에 대해 토론해봐요!

### ISSUE THREAD

**Issue by tgyuuAn** [pknu-wap/2024Study-Objects#5]
### 페이지

pp 33

-----
## 궁금한 내용

궁금한 건 아니고,

![image](https://github.com/user-attachments/assets/02891fbf-39df-4ff9-b8fc-b5815937590b)

이 경우에 **Bag과 TicketOffice를 자율적인 존재로 만들기 vs 의존성이 추가되므로 그냥 그대로 냅두기**

어떤 것을 근거로 결정하였는지 토론해보면 정말 유익할 것 같아요~

**Comment by 9kyo-hwang** [comment]
노론: Bag을 수동적 존재로 두고 의존성을 추가하지 않아도 된다.
소론: Bag이 어떻게 확장될 지 모르기 때문에, 능동적 존재로 두는 것이 더 이득이다.
