### ISSUE TITLE
[1주차] 왜 객체 지향인가?

### ISSUE THREAD

**Issue by dohyeondol1** [pknu-wap/2024Study-Objects#6]
### 페이지
주제에 대한 내용입니덩

-----
## 궁금한 내용
뻔하디뻔한 질문인데....여러분들이 왜 객체 지향을 배우고자 하는지, 객체 지향 프로그래밍을 하는 이유가 뭔지 궁금합니다. 무언가를 배울때엔, 항상 왜 배우는지가 뚜렷해야 한다고 생각하는데, 저는 객체 지향을 배우고자 하는 목표도 있지만, 스터디와책을 통해서 저보다 경험이 많은 사람들은 어떻게 코드를 쓰고, 생각하는지도 배우고자 하는 목표가 있어서 스터디에 참가한 경향이 더 큰 것 같습니다.

**Comment by 9kyo-hwang** [comment]
무의식적으로 짜는 절차지향 코드, 이후에 고치려고 해도 어떻게 고칠 지 모르겠는 코드... 이 상황을 탈피하고 싶어서 열었습니다

**Comment by Redish03** [comment]
저도 아직 프로젝트 경험이 많은 편이라서 단언 할 수는 없겠지만...프젝 하면서 어떤 내용을 추가해야하는데 그러면 고쳐야 할 코드가 많아지고, 여러 파일들을 왔다갔다하면서 뭔가 잘못되지 않았나,,라고 생각만 했지만, 문제가 뭔지는 몰랐습니다.

군대 안에서 책을 읽다보니 클린 아키텍쳐 이런것도 읽는데 프로젝트를 하면서 구조를 잘못짰었나 생각하게 되었고, 어떻게하면 더 깔끔하게 설계하고 유지보수가 용이하도록 할지를 좀 더 고민해봐야 겠다고 생각해서 하게 되었읍니다
