### ISSUE TITLE
[1주차] 절차지향과 객체지향을 적절한 상황?

### ISSUE THREAD

**Issue by gjsk132** [pknu-wap/2024Study-Objects#7]
### 페이지

그냥 책을 읽다가 든 생각이라... 페이지는 딱히 없습니다!

## 궁금한 내용

책을 읽다보니 주어진 상황에 따라서 절차지향과 객체지향을 적절하게 사용해야 한다고 하던데...

확 와닿을 수 있는 예시가 있을까요?

**Comment by HyeonJun-Jung** [comment]
대부분의 상황에서 객체지향이 더 좋은 것 같습니다.
간단하거나 속도가 중요한 프로그램이면 절차지향을 사용해도 좋을 것 같습니다.
