### ISSUE TITLE
[2주차] 상속과 합성을 선택할 때의 기준?

### ISSUE THREAD

**Issue by 9kyo-hwang** [pknu-wap/2024Study-Objects#9]
### 페이지
72p

> 그렇다고 해서 상속을 절대 사용하지 말라는 것은 아니다. 대부분의 설계에서는 상속과 합성을 함께 사용해야 한다. (중략) 코드를 재사용하는 경우에는 상속보다 합성을 선호하는 것이 옳지만 다형성을 위해 인터페이스를 재사용하는 경우에는 상속과 합성을 함께 조합해서 사용할 수밖에 없다.

-----
## 궁금한 내용
인터페이스를 재사용하는 경우 상속을 사용할 수 밖에 없다고는 하는데, 일부 경우를 제외하고는 인터페이스를 재정의하는 오버헤드가 있더라도 합성으로 어지간하면 커버 가능한 것이 아닌가? 라는 의문점이 있네요.

게임 개발을 예로 들면, 언리얼 엔진의 경우 어떤 물체를 생성할 때 프레임워크에서 기본으로 제공하는 `AActor` 같은 것들을 상속받도록 강제하는 반면 유니티의 경우 엔진의 이벤트 함수를 사용하기 위해 `MonoBehaviour`를 상속받도록 기본 세팅돼있는 거 말고는 아무것도 강제하지 않습니다. 이 점에서 엔진의 입문 난이도가 높다고 평가되기도 합니다. 

또한 유니티의 경우 모든 요소를 컴포넌트로 다루도록 설계되어 있고, 언리얼 엔진도 개발사에서 직접 제공하는 샘플 프로젝트의 경우 거의 모든 요소를 컴포넌트화 시켜서 다루도록 코드가 작성되어 있습니다.

그렇다면 상속은 최소화하고 가능하다면 조합으로 처리하는 것이 좀 더 낫지 않나란 생각이 드는데, 설계 상에서 상속이 조합에 비해 유리한 점? 상속이 있어야만 하는 기준? 같은 게 있다면 어떤 게 있을까요?

**Comment by HyeonJun-Jung** [comment]
상속 : 유지 보수 측면에서 상속이 깊어질수록 힘들어진다. & 컴파일 타임 의존성
합성 : 유지 보수 측면에서 효율적 (Component만 관리해주면 됨) & 런타임 의존성
상속과 합성을 적절히 조합해서 사용하는 것이 중요!

**Comment by gjsk132** [comment]
@tgyuuAn님의 완벽한 이미지 설명 👍 
![image](https://github.com/user-attachments/assets/622991cf-1b4a-4397-90dd-451e7751d065)
